name: MP_Linux

on: 
  push:
    paths:
      - '.github/**'
      - 'mp/src/**'
  pull_request:
   paths:
      - 'mp/src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            mp/src

      - name: Configure dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib g++-multilib

      - name: Create project
        working-directory: mp/src
        run: devtools/bin/vpc /sdk2013ce +dedicated /mksln Game

      - name: Build project
        working-directory: mp/src
        run: make -f Game.mak

      - name: Upload package
        uses: actions/upload-artifact@v4.4.3
        with:
          name: hl2dm-coopbase-lin
          compression-level: 9
          path: |
            mp/game/mod_coopbase/bin/
            !**/*.dbg
